#Fichier de proprietes relatives a la LUT
#Fri Feb 27 13:11:31 CET 2026
lut.store.addedDirection=false
lut.store.coupl=true
lut.store.iterx=false
lut.generate=true
lut.store.atmosToa=false
lut.store.reflectance=false
lut.store.luminance=true
lut.store.toa=false
lut.store.ordre=false
lut.store.fluorescence=false
lut.store.indirect=false
lut.store.atmosToaOrdre=false
lut.pathToDatabase=DART_PT_mode_R\\DART_PT_mode_R.db
lut.store.sensor=false
lut.store.productsPerType=false
lut.store.otherIter=false
lut.store.maketCoverage=false
lut.sequenceName=DART_PT_mode_R
